### ISSUE TITLE
CocoaPods does not have 0.4.4 release

### ISSUE THREAD

**Issue by mjarvis** [Anviking/Decodable#114]
Would be nice to have 0.4.4 pushed to cocoapods trunk. Last version shown there is 0.4.3
https://cocoapods.org/pods/Decodable

**Comment by irace** [comment]
Please push 0.4.4 to CocoaPods, otherwise those of using Swift 2.3 are unable to build apps that depend on Decodable.

**Comment by Anviking** [comment]
Sorry, I was having problems with it before (or not supported?), and while recently managed to push 0.5 with latest cocoapods rc, I cannot figure out how to push 0.4.4:

It's complaining on `SWIFT_VERSION` not being set (which to my best knowledge it is).
<details>
```
~/D/Decodable  ➤ 0.4.4  pod trunk push Decodable.podspec --verbose                           (18s 922ms)

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     d73c42f..7e0d125  master     -> origin/master
  Updating d73c42f..7e0d125
  Fast-forward
   Specs/DCKit/1.0.6/DCKit.podspec.json | 21 +++++++++++++++++++++
   1 file changed, 21 insertions(+)
   create mode 100644 Specs/DCKit/1.0.6/DCKit.podspec.json

CocoaPods 1.1.0.rc.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Validating podspec
    Decodable (0.4.4) - Analyzing on iOS 8.0 platform.
  Preparing
[!] Unable to load a specification for the plugin `/Users/Johannes/.rvm/gems/ruby-2.2.0/gems/cocoapods-deintegrate-1.0.1`

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `Decodable` from `/Users/Johannes/Developer/Decodable/Decodable.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A Decodable

Downloading dependencies

-> Installing Decodable (0.4.4)
  > Copying Decodable from
  `/Users/Johannes/Library/Caches/CocoaPods/Pods/External/Decodable/dbc8d314c1752d2f9c2b402472a7c9b2-07ebb`
  to `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Decodable`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Decodable` iOS 8.0
      - Generating Info.plist file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Decodable.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Decodable-umbrella.h`
    - Installing target `Pods` iOS 8.0
      - Generating Info.plist file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Pods.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Pods-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to
  `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in
  `../../../../var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Podfile.lock`
  - Writing Manifest in
  `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`
  - Running post install hooks
  Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild.
xcodebuild clean build -target Pods CODE_SIGN_IDENTITY=- -sdk iphonesimulator 2>&1
2016-09-14 20:40:11.047 xcodebuild[25063:7009843] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7ff7cf328d60:'/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
2016-09-14 20:40:11.048 xcodebuild[25063:7009843] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7ff7cf328df0:'/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = iphonesimulator10.0

=== CLEAN TARGET Decodable OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
=== BUILD TARGET Decodable OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
    Decodable (0.4.4) - Analyzing on OS X 10.9 platform.
  Preparing
[!] Unable to load a specification for the plugin `/Users/Johannes/.rvm/gems/ruby-2.2.0/gems/cocoapods-deintegrate-1.0.1`

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `Decodable` from `/Users/Johannes/Developer/Decodable/Decodable.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A Decodable

Downloading dependencies

-> Installing Decodable (0.4.4)
  > Copying Decodable from
  `/Users/Johannes/Library/Caches/CocoaPods/Pods/External/Decodable/dbc8d314c1752d2f9c2b402472a7c9b2-07ebb`
  to `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Decodable`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Decodable` OS X 10.9
      - Generating Info.plist file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Decodable.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Decodable-umbrella.h`
    - Installing target `Pods` OS X 10.9
      - Generating Info.plist file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Pods.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Pods-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to
  `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in
  `../../../../var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Podfile.lock`
  - Writing Manifest in
  `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`
  - Running post install hooks
  Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild.
xcodebuild clean build -target Pods 2>&1
2016-09-14 20:40:12.253 xcodebuild[25085:7009922] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7f9f92d46a30:'/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
2016-09-14 20:40:12.253 xcodebuild[25085:7009922] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7f9f92d46ac0:'/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
=== CLEAN TARGET Decodable OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
=== BUILD TARGET Decodable OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
    Decodable (0.4.4) - Analyzing on tvOS 9.0 platform.
  Preparing
[!] Unable to load a specification for the plugin `/Users/Johannes/.rvm/gems/ruby-2.2.0/gems/cocoapods-deintegrate-1.0.1`

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `Decodable` from `/Users/Johannes/Developer/Decodable/Decodable.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A Decodable

Downloading dependencies

-> Installing Decodable (0.4.4)
  > Copying Decodable from
  `/Users/Johannes/Library/Caches/CocoaPods/Pods/External/Decodable/dbc8d314c1752d2f9c2b402472a7c9b2-07ebb`
  to `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Decodable`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Decodable` tvOS 9.0
      - Generating Info.plist file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Decodable.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Decodable-umbrella.h`
    - Installing target `Pods` tvOS 9.0
      - Generating Info.plist file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Pods.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Pods-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to
  `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in
  `../../../../var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Podfile.lock`
  - Writing Manifest in
  `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`
  - Running post install hooks
  Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild.
xcodebuild clean build -target Pods CODE_SIGN_IDENTITY=- -sdk appletvsimulator 2>&1
2016-09-14 20:40:13.271 xcodebuild[25101:7009983] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7fb3597b6f80:'/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
2016-09-14 20:40:13.271 xcodebuild[25101:7009983] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7fb3597b7010:'/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = appletvsimulator10.0

=== CLEAN TARGET Decodable OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
=== BUILD TARGET Decodable OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
    Decodable (0.4.4) - Analyzing on watchOS 2.0 platform.
  Preparing
[!] Unable to load a specification for the plugin `/Users/Johannes/.rvm/gems/ruby-2.2.0/gems/cocoapods-deintegrate-1.0.1`

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `Decodable` from `/Users/Johannes/Developer/Decodable/Decodable.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A Decodable

Downloading dependencies

-> Installing Decodable (0.4.4)
  > Copying Decodable from
  `/Users/Johannes/Library/Caches/CocoaPods/Pods/External/Decodable/dbc8d314c1752d2f9c2b402472a7c9b2-07ebb`
  to `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Decodable`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Decodable` watchOS 2.0
      - Generating Info.plist file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Decodable.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Decodable/Decodable-umbrella.h`
    - Installing target `Pods` watchOS 2.0
      - Generating Info.plist file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Pods.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods/Pods-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to
  `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in
  `../../../../var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Podfile.lock`
  - Writing Manifest in
  `../../../../private/var/folders/p9/t36w85qs5qz0p7gy_cn7r8wm0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`
  - Running post install hooks
  Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild.
xcodebuild clean build -target Pods CODE_SIGN_IDENTITY=- -sdk watchsimulator 2>&1
2016-09-14 20:40:14.221 xcodebuild[25117:7010027] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7fdd8f471b70:'/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
2016-09-14 20:40:14.222 xcodebuild[25117:7010027] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7fdd8f471c00:'/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = watchsimulator3.0

=== CLEAN TARGET Decodable OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
=== BUILD TARGET Decodable OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
 -> Decodable (0.4.4)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.

[!] The podspec does not validate.

/Users/Johannes/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:114:in `validate_podspec'
/Users/Johannes/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:59:in `run'
/Users/Johannes/.rvm/gems/ruby-2.2.0@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/Johannes/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/Johannes/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/Johannes/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/Johannes/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/Johannes/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/Johannes/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```
</details>

Additionally, I thought setting `SWIFT_VERSION` in your podspec on a release targeting Swift 2.2 was a common workaround. Does that not work here? (The only difference between Decodable's 0.4.4 and v0.4.3 is the `SWIFT_VERSION` setting)

**Comment by alexito4** [comment]
Any workaround for this?

**Comment by mjarvis** [comment]
@alexito4 Use this in your podfile:
`pod 'Decodable', :git => 'https://github.com/Aniviking/Decodable.git', :tag => '0.4.4'`
or `pod 'Decodable', :git => 'git@github.com:Aniviking/Decodable.git', :tag => '0.4.4'` if you use ssh urls

**Comment by alexito4** [comment]
The issue comes when you want to do that in a Podspec for the private frameworks that your apps use.
